require("mowais.plugins-setup")
require("mowais.core.options")
require("mowais.core.keymaps")
require("mowais.core.colorscheme")
require("mowais.plugins.comment")
require("mowais.plugins.nvim-tree")
require("mowais.plugins.lualine")
require("mowais.plugins.telescope")
require("mowais.plugins.nvim-cmp")
require("mowais.plugins.lsp.mason")
require("mowais.plugins.lsp.lspconfig")
require("mowais.plugins.lsp.lspsaga")
require("mowais.plugins.autopairs")
require("mowais.plugins.treesitter")
require("mowais.plugins.gitsigns")

